### ISSUE TITLE
Organize the project into MVC Design Pattern

### ISSUE THREAD

**Issue by amit-trivedi-7** [7thalaforareason/stackoverflow-clone#1]
The API needs to be organized in MVC (Model-View-Controller) design pattern.

### Tasks
- [ ] Create models, controllers, routes folders.
- [ ] Configure MongoDB Connection
- [x] #2

**Comment by shaharsh624** [comment]
/assign

Please assign this issue to me. I am proficient in organizing project structure.

**Comment by amit-trivedi-7** [comment]
The Issue #1 is now closed.
