### ISSUE TITLE
Create Controllers for operations of users, questions, answers, comments

### ISSUE THREAD

**Issue by shaharsh624** [7thalaforareason/stackoverflow-clone#5]
The project needs controllers to function. Please accept this issue and assign me.
/assign

Create Contollers for all 4 mongodb models.

- [ ] Users
- [ ] Questions
- [ ] Answers
- [ ] Comments

**Comment by shaharsh624** [comment]
Please assign me this issue

/assign

**Comment by amit-trivedi-7** [comment]
The Issue #5 is now closed.
